# 服务端口号
server:
  port: 8761
# 服务应用名
spring:
  application:
    name: eureka_service1
  freemarker:
    prefer-file-system-access: false
eureka:
#   防止由于Eureka的机制导致Client被错误显示在线，仅在开发环境使用
  server:
    enable-self-preservation: true
  client:
#   表示服务不注册到注册中心, 该服务作为服务中心
    register-with-eureka: false
#    表示不从Eureka中心获取到注册的信息
    fetch-registry: false
#   Eureka注册中心服务访问地址
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#      开启多机部署
#      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka,http://localhost:8763/eureka

#


#server:
#  port: 8088 # 端口
#spring:
#  application:
#    name: eurekaserverdemo # 应用名称，会在Eureka中显示
#eureka:
#  client:
#    register-with-eureka: false # 是否注册自己的信息到EurekaServer，默认是true
#    fetch-registry: false # 是否拉取其它服务的信息，默认是true
#    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
#      defaultZone: http://localhost:8088/eureka
